### ISSUE TITLE
Alterações Necessárias

### ISSUE THREAD

**Issue by nicolasmagalhaes** [Sergiorezende22/QuickSell#6]
- [x] Adicionar caso de uso editar proposta
- [x] Remover caso de uso enviar mensagem
- [x] Adicionar caso de uso para Registrar que o imóvel foi vendido
- [x] Adicionar regra de negócio para definir oq precisa na proposta
- [x] Editar caso de uso Emitir Relatório
- [x] Gerar os pngs novamente depois de terminar

**Comment by nicolasmagalhaes** [comment]
Será que registrar que o imóvel foi vendido é realmente um caso de uso? Ou pode ser apenas um parâmetro que podemos adicionar na proposta?

**Comment by Sergiorezende22** [comment]
Resolvido
